# Generated by Django 5.2.12 on 2026-03-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('vaccination', '疫苗提醒'), ('deworming', '驱虫提醒')], max_length=20, verbose_name='提醒类型')),
                ('title', models.CharField(max_length=120, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('pet_name', models.CharField(blank=True, max_length=50, verbose_name='宠物名称')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('source_model', models.CharField(max_length=30, verbose_name='来源模型')),
                ('source_id', models.PositiveBigIntegerField(verbose_name='来源记录ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '站内信提醒',
                'verbose_name_plural': '站内信提醒',
                'db_table': 'notification',
                'ordering': ['is_read', 'due_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'message_type', 'source_model', 'source_id'), name='uniq_user_notification_source'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notification_user_id_35b8dc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'due_date'], name='notification_user_id_2c954a_idx'),
        ),
    ]
