# Generated by Django 5.2.12 on 2026-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('就诊', '就诊'), ('体检', '体检'), ('体重', '体重'), ('驱虫', '驱虫'), ('过敏', '过敏'), ('手术', '手术'), ('其他', '其他')], max_length=20, verbose_name='记录类型')),
                ('record_date', models.DateField(verbose_name='记录日期')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, verbose_name='详细内容')),
                ('hospital', models.CharField(blank=True, max_length=100, verbose_name='医院名称')),
                ('doctor', models.CharField(blank=True, max_length=50, verbose_name='医生姓名')),
                ('cost', models.FloatField(blank=True, null=True, verbose_name='费用')),
                ('attachment', models.FileField(blank=True, upload_to='health_records/', verbose_name='附件')),
                ('next_check_date', models.DateField(blank=True, null=True, verbose_name='下次复查日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '健康记录',
                'verbose_name_plural': '健康记录',
                'db_table': 'health_record',
                'ordering': ['-record_date'],
            },
        ),
    ]
