# Generated by Django 5.2.12 on 2026-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='宠物名称')),
                ('breed', models.CharField(blank=True, max_length=100, verbose_name='品种')),
                ('gender', models.CharField(blank=True, choices=[('公', '公'), ('母', '母'), ('未知', '未知')], max_length=10, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='体重(kg)')),
                ('color', models.CharField(blank=True, max_length=50, verbose_name='毛色')),
                ('chip_number', models.CharField(blank=True, max_length=50, verbose_name='芯片号')),
                ('description', models.TextField(blank=True, verbose_name='特征描述')),
                ('personality', models.TextField(blank=True, verbose_name='性格特点')),
                ('avatar', models.ImageField(blank=True, upload_to='pets/', verbose_name='宠物头像')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '宠物',
                'verbose_name_plural': '宠物',
                'db_table': 'pet',
                'ordering': ['-created_at'],
            },
        ),
    ]
