# Generated by Django 5.2.12 on 2026-03-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('food', '食物'), ('medical', '医疗'), ('grooming', '美容'), ('supplies', '用品'), ('insurance', '保险'), ('other', '其他')], max_length=20, verbose_name='消费分类')),
                ('expense_date', models.DateField(verbose_name='消费日期')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('merchant', models.CharField(blank=True, max_length=100, verbose_name='商家名称')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('attachment', models.FileField(blank=True, upload_to='expenses/', verbose_name='小票/凭证')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '消费记录',
                'verbose_name_plural': '消费记录',
                'db_table': 'expense',
                'ordering': ['-expense_date'],
            },
        ),
    ]
