# Generated by Django 5.2.12 on 2026-03-14 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='疫苗名称')),
                ('vaccination_date', models.DateField(verbose_name='接种日期')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='下次接种日期')),
                ('clinic', models.CharField(blank=True, max_length=100, verbose_name='接种单位')),
                ('doctor', models.CharField(blank=True, max_length=50, verbose_name='医生姓名')),
                ('batch_number', models.CharField(blank=True, max_length=50, verbose_name='疫苗批次号')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('attachment', models.FileField(blank=True, upload_to='vaccinations/', verbose_name='附件')),
                ('is_reminded', models.BooleanField(default=False, verbose_name='是否已提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='pets.pet', verbose_name='宠物')),
            ],
            options={
                'verbose_name': '疫苗记录',
                'verbose_name_plural': '疫苗记录',
                'db_table': 'vaccination',
                'ordering': ['-vaccination_date'],
            },
        ),
    ]
